table sales
	lineageTag: 5bef085c-6d03-4d9c-bb32-645be642ecf6
	sourceLineageTag: [dbo].[sales]

	measure 'Total Fake Measure 1' = =SUM(sales[Fake_Measure_1])
		formatString: #,##0
		lineageTag: 2ad37559-1032-4b68-ac59-e58d22ec40ca

	measure 'Total Fake Measure 2' = =SUM(sales[Fake_Measure_2])
		formatString: #,##0
		lineageTag: a1cd0982-e88c-47a0-bf10-daf13dcca896

	measure 'Total Fake Measure 3' = =SUM(sales[Fake_Measure_3])
		formatString: #,##0
		lineageTag: 8532b194-cd6b-454d-b8bc-17f3b9cbb25b

	measure 'Total Fake Measure 4' = =SUM(sales[Fake_Measure_4])
		formatString: #,##0
		lineageTag: 2c969026-ea04-4216-86c1-fba43ca00321

	measure 'Total Fake Measure 5' = =SUM(sales[Fake_Measure_5])
		formatString: #,##0
		lineageTag: 486b1cf0-f6d4-4a75-b006-3812b1cc9183

	measure 'Total Fake Measure 6' = =SUM(sales[Fake_Measure_6])
		formatString: #,##0
		lineageTag: 3133be73-8be6-4109-95e6-7b42acf93da4

	measure 'Total Fake Measure 7' = =SUM(sales[Fake_Measure_7])
		formatString: #,##0
		lineageTag: deafd372-7e39-48e8-9f18-96e7cf6a756f

	measure 'Total Fake Measure 8' = =SUM(sales[Fake_Measure_8])
		formatString: #,##0
		lineageTag: 1118f2f4-758f-4054-86dd-7f44bad91769

	measure 'Total Fake Measure 9' = =SUM(sales[Fake_Measure_9])
		formatString: #,##0
		lineageTag: d032d038-0858-463a-800a-1d811f44e12f

	measure 'Total Fake Measure 10' = =SUM(sales[Fake_Measure_10])
		formatString: #,##0
		lineageTag: 2ccf420f-1e7e-45f8-94dd-e2221a96d710

	measure 'Total Fake Measure 11' = =SUM(sales[Fake_Measure_11])
		formatString: #,##0
		lineageTag: 093bef3c-0db7-470f-8b05-af7b0c251ea4

	measure 'Total Fake Measure 12' = =SUM(sales[Fake_Measure_12])
		formatString: #,##0
		lineageTag: a1f55c86-e95f-44a6-a956-b3566c3a3289

	measure 'Total Fake Measure 13' = =SUM(sales[Fake_Measure_13])
		formatString: #,##0
		lineageTag: 1cbdbd08-0dd8-4b79-954b-82eb1d399892

	measure 'Total Fake Measure 14' = =SUM(sales[Fake_Measure_14])
		formatString: #,##0
		lineageTag: 1939c46e-c32e-431c-97a8-a3cf1d712228

	measure 'Total Fake Measure 15' = =SUM(sales[Fake_Measure_15])
		formatString: #,##0
		lineageTag: 24d8d283-fa73-429d-83fd-0b8a4cff16f3

	measure 'Total Fake Measure 16' = =SUM(sales[Fake_Measure_16])
		formatString: #,##0
		lineageTag: 73a2f541-8472-4aa2-bbe1-4c7c463e6d78

	measure 'Total Fake Measure 17' = =SUM(sales[Fake_Measure_17])
		formatString: #,##0
		lineageTag: 0920e9cd-567b-4948-8291-fe6304f94bfb

	measure 'Total Fake Measure 18' = =SUM(sales[Fake_Measure_18])
		formatString: #,##0
		lineageTag: 67c07f60-1584-454c-a84b-2588fdcc4a14

	measure 'Total Fake Measure 19' = =SUM(sales[Fake_Measure_19])
		formatString: #,##0
		lineageTag: 4c77dc75-3d13-4fbe-ac94-73d01c991f10

	measure 'Total Fake Measure 20' = =SUM(sales[Fake_Measure_20])
		formatString: #,##0
		lineageTag: 3a038542-7b2b-48ef-ba45-bff89dca07d5

	measure 'Total Fake Measure 21' = =SUM(sales[Fake_Measure_21])
		formatString: #,##0
		lineageTag: fea6b700-7c9e-4992-992a-0d9d59a2de03

	measure 'Total Fake Measure 22' = =SUM(sales[Fake_Measure_22])
		formatString: #,##0
		lineageTag: 25d3f3e9-d619-49d1-acc0-f076a0cf6558

	measure 'Total Fake Measure 23' = =SUM(sales[Fake_Measure_23])
		formatString: #,##0
		lineageTag: ee4fe802-c458-4225-b466-388094a2e9c4

	measure 'Total Fake Measure 24' = =SUM(sales[Fake_Measure_24])
		formatString: #,##0
		lineageTag: 56720152-b481-4000-bc41-1446cf9adb8b

	measure 'Total Fake Measure 25' = =SUM(sales[Fake_Measure_25])
		formatString: #,##0
		lineageTag: 2fb4aa82-1d7a-4c0a-8c75-9a7d2cb3237e

	measure 'Total Fake Measure 26' = =SUM(sales[Fake_Measure_26])
		formatString: #,##0
		lineageTag: 7648e993-2d43-4c7e-96a3-632bf4c8c9da

	measure 'Total Fake Measure 27' = =SUM(sales[Fake_Measure_27])
		formatString: #,##0
		lineageTag: b1c88630-8b43-4b05-bb60-a8e3494677f0

	measure 'Total Fake Measure 28' = =SUM(sales[Fake_Measure_28])
		formatString: #,##0
		lineageTag: 7bfe6af6-cff6-4efa-8cc2-05bcee36b024

	measure 'Total Fake Measure 29' = =SUM(sales[Fake_Measure_29])
		formatString: #,##0
		lineageTag: 614f70d8-8796-4bdf-9525-f72bac596dfe

	measure 'Total Fake Measure 30' = =SUM(sales[Fake_Measure_30])
		formatString: #,##0
		lineageTag: 3a55e620-9d03-4c00-8299-5c9bd505d27d

	measure 'Total Fake Measure 31' = =SUM(sales[Fake_Measure_31])
		formatString: #,##0
		lineageTag: 9ddfa77f-7200-47b4-81eb-5d86e275b5d4

	measure 'Total Fake Measure 32' = =SUM(sales[Fake_Measure_32])
		formatString: #,##0
		lineageTag: ab3a6fbb-1986-44be-87cf-97ba97634c7e

	measure 'Total Fake Measure 33' = =SUM(sales[Fake_Measure_33])
		formatString: #,##0
		lineageTag: 9000a031-125d-4c6d-a297-51421bcd79c2

	measure 'Total Fake Measure 34' = =SUM(sales[Fake_Measure_34])
		formatString: #,##0
		lineageTag: 6a9f7c0b-ff95-45ec-a2a5-78bb8efefa21

	measure 'Total Fake Measure 35' = =SUM(sales[Fake_Measure_35])
		formatString: #,##0
		lineageTag: a5258dca-b825-499e-818b-424d147730c3

	measure 'Total Fake Measure 36' = =SUM(sales[Fake_Measure_36])
		formatString: #,##0
		lineageTag: a4f62ec5-1385-4711-8792-71d6dc13d284

	measure 'Total Fake Measure 37' = =SUM(sales[Fake_Measure_37])
		formatString: #,##0
		lineageTag: e9e83084-e5a4-40dd-be34-b1c067e7b149

	measure 'Total Fake Measure 38' = =SUM(sales[Fake_Measure_38])
		formatString: #,##0
		lineageTag: cbf1dcd6-d06b-4551-89df-8fdcc91f2c38

	measure 'Total Fake Measure 39' = =SUM(sales[Fake_Measure_39])
		formatString: #,##0
		lineageTag: 57eb3aab-9094-40a8-8596-4c16fb0dcb25

	measure 'Total Fake Measure 40' = =SUM(sales[Fake_Measure_40])
		formatString: #,##0
		lineageTag: d95803d0-e630-42d8-93c7-15c088cc5d6c

	measure 'Total Fake Measure 41' = =SUM(sales[Fake_Measure_41])
		formatString: #,##0
		lineageTag: f3acf6e5-c77b-413c-b1b5-269250756a8d

	measure 'Total Fake Measure 42' = =SUM(sales[Fake_Measure_42])
		formatString: #,##0
		lineageTag: d97e607e-648b-4b39-a1f8-4c34ea25fc7b

	measure 'Total Fake Measure 43' = =SUM(sales[Fake_Measure_43])
		formatString: #,##0
		lineageTag: c7f2ea72-f45a-45d8-91c9-8b3df406e945

	measure 'Total Fake Measure 44' = =SUM(sales[Fake_Measure_44])
		formatString: #,##0
		lineageTag: f44af3b2-28a4-43fd-906a-caecd3824576

	measure 'Total Fake Measure 45' = =SUM(sales[Fake_Measure_45])
		formatString: #,##0
		lineageTag: 09374340-e1d5-4582-b0ce-afd3a879f291

	measure 'Total Fake Measure 46' = =SUM(sales[Fake_Measure_46])
		formatString: #,##0
		lineageTag: 223d8a4e-fd48-4da3-bdfa-0cfd9a80137a

	measure 'Total Fake Measure 47' = =SUM(sales[Fake_Measure_47])
		formatString: #,##0
		lineageTag: 813b4d22-668b-4e0b-821a-fdab03f54cf5

	measure 'Total Fake Measure 48' = =SUM(sales[Fake_Measure_48])
		formatString: #,##0
		lineageTag: 118ede8c-dd80-4d9d-a120-30b3f1730f0e

	measure 'Total Fake Measure 49' = =SUM(sales[Fake_Measure_49])
		formatString: #,##0
		lineageTag: d298147e-cfd8-4344-9afa-f2f0c6f8429d

	measure 'Total Fake Measure 50' = =SUM(sales[Fake_Measure_50])
		formatString: #,##0
		lineageTag: be4f3915-a80c-4754-a519-428f5d77bd4c

	measure 'Total Fake Measure 51' = =SUM(sales[Fake_Measure_51])
		formatString: #,##0
		lineageTag: 11ee773d-6649-4ab0-b1d2-16978c74f23c

	measure 'Total Fake Measure 52' = =SUM(sales[Fake_Measure_52])
		formatString: #,##0
		lineageTag: e01ea8bf-6a19-4a59-81e9-1abec21daf3e

	measure 'Total Fake Measure 53' = =SUM(sales[Fake_Measure_53])
		formatString: #,##0
		lineageTag: 864fcb58-c2ea-43e1-ab2f-a39d1e32a10b

	measure 'Total Fake Measure 54' = =SUM(sales[Fake_Measure_54])
		formatString: #,##0
		lineageTag: 12e8ac79-ae29-483e-80ff-704c31030782

	measure 'Total Fake Measure 55' = =SUM(sales[Fake_Measure_55])
		formatString: #,##0
		lineageTag: ebc9dd19-0281-4542-8c5f-d73041b6b1dd

	measure 'Total Fake Measure 56' = =SUM(sales[Fake_Measure_56])
		formatString: #,##0
		lineageTag: 5495a2aa-dc05-4d4d-9ee2-a52dcd3277b4

	measure 'Total Fake Measure 57' = =SUM(sales[Fake_Measure_57])
		formatString: #,##0
		lineageTag: 62b0a2b1-a781-42f5-89b6-e58adaf03efa

	measure 'Total Fake Measure 58' = =SUM(sales[Fake_Measure_58])
		formatString: #,##0
		lineageTag: 60d334b5-b06a-4ae4-9dbd-89f3c05a5708

	measure 'Total Fake Measure 59' = =SUM(sales[Fake_Measure_59])
		formatString: #,##0
		lineageTag: 9d593ba2-485d-4c78-b0d4-3205357d901c

	measure 'Total Fake Measure 60' = =SUM(sales[Fake_Measure_60])
		formatString: #,##0
		lineageTag: c89d9432-2b08-45da-9cc2-78a01d41fb32

	measure 'Total Fake Measure 61' = =SUM(sales[Fake_Measure_61])
		formatString: #,##0
		lineageTag: 8e0bf993-e845-4510-a023-b1b0bab8289e

	measure 'Total Fake Measure 62' = =SUM(sales[Fake_Measure_62])
		formatString: #,##0
		lineageTag: 1cc811d5-e233-4bf3-94ce-533731c8568a

	measure 'Total Fake Measure 63' = =SUM(sales[Fake_Measure_63])
		formatString: #,##0
		lineageTag: 0511c7fc-632e-40c3-9586-3f7eced98174

	measure 'Total Fake Measure 64' = =SUM(sales[Fake_Measure_64])
		formatString: #,##0
		lineageTag: 66272d62-993a-43f9-988f-ba5f0ad72879

	measure 'Total Fake Measure 65' = =SUM(sales[Fake_Measure_65])
		formatString: #,##0
		lineageTag: 1f4152ba-91be-4a8f-b264-af4316cb03aa

	measure 'Total Fake Measure 66' = =SUM(sales[Fake_Measure_66])
		formatString: #,##0
		lineageTag: fbce49c2-f4cf-404e-99dc-fd38850ef0e6

	measure 'Total Fake Measure 67' = =SUM(sales[Fake_Measure_67])
		formatString: #,##0
		lineageTag: 51985484-404e-4e9a-b041-253a4f26ad11

	measure 'Total Fake Measure 68' = =SUM(sales[Fake_Measure_68])
		formatString: #,##0
		lineageTag: ffc5f6be-b20b-4e4b-932a-0077df448aa9

	measure 'Total Fake Measure 69' = =SUM(sales[Fake_Measure_69])
		formatString: #,##0
		lineageTag: 22db8411-dbe5-4e6d-8608-bd55d59120bd

	measure 'Total Fake Measure 70' = =SUM(sales[Fake_Measure_70])
		formatString: #,##0
		lineageTag: 73fb8c1c-6a81-466a-8925-4b91fc836423

	measure 'Total Fake Measure 71' = =SUM(sales[Fake_Measure_71])
		formatString: #,##0
		lineageTag: 71ebcd9a-da22-46d1-9b9f-267baddf5f00

	measure 'Total Fake Measure 72' = =SUM(sales[Fake_Measure_72])
		formatString: #,##0
		lineageTag: e37fc564-c3d0-445a-addd-b60a006bf127

	measure 'Total Fake Measure 73' = =SUM(sales[Fake_Measure_73])
		formatString: #,##0
		lineageTag: b9242b9d-6cbd-4ae5-9df5-85e3a792b5ff

	measure 'Total Fake Measure 74' = =SUM(sales[Fake_Measure_74])
		formatString: #,##0
		lineageTag: ffe1bc81-6536-415e-a60e-1803ee0ca192

	measure 'Total Fake Measure 75' = =SUM(sales[Fake_Measure_75])
		formatString: #,##0
		lineageTag: 496c4485-4197-4fc3-a42b-17c4be95335f

	measure 'Total Fake Measure 76' = =SUM(sales[Fake_Measure_76])
		formatString: #,##0
		lineageTag: aa1e2964-ab19-4d24-8318-c483ebf71187

	measure 'Total Fake Measure 77' = =SUM(sales[Fake_Measure_77])
		formatString: #,##0
		lineageTag: 03705818-110f-41e9-ba37-0d9ddee79ce1

	measure 'Total Fake Measure 78' = =SUM(sales[Fake_Measure_78])
		formatString: #,##0
		lineageTag: c22221f9-0fee-43b4-a0a1-7add96a9d528

	measure 'Total Fake Measure 79' = =SUM(sales[Fake_Measure_79])
		formatString: #,##0
		lineageTag: 55704b55-cbe3-4688-a326-aa006e5f3bf3

	measure 'Total Fake Measure 80' = =SUM(sales[Fake_Measure_80])
		formatString: #,##0
		lineageTag: 1c74e02a-2bfc-4e67-8405-9a5bcef9813a

	measure 'Total Fake Measure 81' = =SUM(sales[Fake_Measure_81])
		formatString: #,##0
		lineageTag: a5cc9208-c65e-4a15-ae5d-c75670891ead

	measure 'Total Fake Measure 82' = =SUM(sales[Fake_Measure_82])
		formatString: #,##0
		lineageTag: d957f70c-ef02-407f-995b-ae806fcb0aca

	measure 'Total Fake Measure 83' = =SUM(sales[Fake_Measure_83])
		formatString: #,##0
		lineageTag: f3f562c1-8f44-4bb5-8ecc-bb7a80b42915

	measure 'Total Fake Measure 84' = =SUM(sales[Fake_Measure_84])
		formatString: #,##0
		lineageTag: ef6cc0b0-1bcb-4083-90c4-ed2a8c307b6d

	measure 'Total Fake Measure 85' = =SUM(sales[Fake_Measure_85])
		formatString: #,##0
		lineageTag: 819cf6b2-5d12-4634-bb80-c3c5b4298dbe

	measure 'Total Fake Measure 86' = =SUM(sales[Fake_Measure_86])
		formatString: #,##0
		lineageTag: c090fd99-db33-4b89-b1da-de4d7b7c51d0

	measure 'Total Fake Measure 87' = =SUM(sales[Fake_Measure_87])
		formatString: #,##0
		lineageTag: f7136088-f80e-4a63-a22e-50a88a49ff94

	measure 'Total Fake Measure 88' = =SUM(sales[Fake_Measure_88])
		formatString: #,##0
		lineageTag: 9639f3b1-c272-472d-a0bd-c5f5f90b78d5

	measure 'Total Fake Measure 89' = =SUM(sales[Fake_Measure_89])
		formatString: #,##0
		lineageTag: cec8917e-17f8-41e2-9918-e647791d8762

	measure 'Total Fake Measure 90' = =SUM(sales[Fake_Measure_90])
		formatString: #,##0
		lineageTag: 413b7ebf-9b8f-4bb8-b667-7b261693fe20

	measure 'Total Fake Measure 91' = =SUM(sales[Fake_Measure_91])
		formatString: #,##0
		lineageTag: 66df1133-5f02-4a9b-964f-a4c3361ce8bd

	measure 'Total Fake Measure 92' = =SUM(sales[Fake_Measure_92])
		formatString: #,##0
		lineageTag: f9add4dd-7a15-4916-a209-3cea63008ea0

	measure 'Total Fake Measure 93' = =SUM(sales[Fake_Measure_93])
		formatString: #,##0
		lineageTag: ac359e32-54c2-4885-a672-bac627d67361

	measure 'Total Fake Measure 94' = =SUM(sales[Fake_Measure_94])
		formatString: #,##0
		lineageTag: 08fb1f15-b68b-4e9f-8515-e28c46c7f74c

	measure 'Total Fake Measure 95' = =SUM(sales[Fake_Measure_95])
		formatString: #,##0
		lineageTag: 44b263d8-2c60-408a-a501-cecc7e125967

	measure 'Total Fake Measure 96' = =SUM(sales[Fake_Measure_96])
		formatString: #,##0
		lineageTag: ac2000c7-465b-4030-842c-d72bb078a811

	measure 'Total Fake Measure 97' = =SUM(sales[Fake_Measure_97])
		formatString: #,##0
		lineageTag: 674c8bbd-c745-42f9-8905-5951efe6399b

	measure 'Total Fake Measure 98' = =SUM(sales[Fake_Measure_98])
		formatString: #,##0
		lineageTag: f1290405-01df-44a7-b648-52dfc56ed963

	measure 'Total Fake Measure 99' = =SUM(sales[Fake_Measure_99])
		formatString: #,##0
		lineageTag: 3a002f82-2906-4306-90b0-c3f4724e5923

	measure 'Total Fake Measure 100' = =SUM(sales[Fake_Measure_100])
		formatString: #,##0
		lineageTag: 65d0c5dc-0f93-4674-95d2-8bd658ed465f

	column customer_key
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 32731e55-f52b-4963-ae49-9266cd268133
		sourceColumn: customer_key

	column store_key
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: b9ad8bf2-928b-4037-964d-4b2fa1d8bd4b
		sourceColumn: store_key

	column product_key
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 32487870-3be6-43ff-b7f8-6952e64b89f9
		sourceColumn: product_key

	column orderdate_key
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		lineageTag: e3f1609d-859c-4418-9b59-a259fb2c38c0
		sourceColumn: orderdate_key

	column deliverydate_key
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		lineageTag: dd1e5fba-09c2-42cf-b6bb-124582f6bbd3
		sourceColumn: deliverydate_key

	column Price
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: b937074d-a9db-4fa1-92df-8293ae27c898
		sourceColumn: Price

	column Qunatity
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 153d0cea-637b-4e94-bdab-08be1781751d
		sourceColumn: Qunatity

	column Cost
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 98a6c6f3-a3a2-4563-865f-573501a434bc
		sourceColumn: Cost

	column Fake_Measure_1
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 623cee35-ee3c-41e7-80c7-f49f3af1b792
		sourceColumn: Fake_Measure_1

	column Fake_Measure_2
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 3826f683-3810-4a79-a041-34f0db9d5c7f
		sourceColumn: Fake_Measure_2

	column Fake_Measure_3
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 3d3d162f-2180-45ec-82c6-b20f26a8f4fb
		sourceColumn: Fake_Measure_3

	column Fake_Measure_4
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: bd88ed18-f1e0-4f2e-8cd7-2ce568711192
		sourceColumn: Fake_Measure_4

	column Fake_Measure_5
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 64c3d377-1d3c-4360-acd9-a11e958529e4
		sourceColumn: Fake_Measure_5

	column Fake_Measure_6
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 87c1205c-651a-4353-9fdb-c0522c5a16af
		sourceColumn: Fake_Measure_6

	column Fake_Measure_7
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 2e68636e-f109-47f4-b809-aeeb9dd91720
		sourceColumn: Fake_Measure_7

	column Fake_Measure_8
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: eaf2cd97-a416-4635-9337-0c54abc79ff1
		sourceColumn: Fake_Measure_8

	column Fake_Measure_9
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 25f3773f-e0ab-4f4a-b1f9-b337558dad78
		sourceColumn: Fake_Measure_9

	column Fake_Measure_10
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: b3dde8bd-f74b-4a71-a59b-b95e2ed7ebfb
		sourceColumn: Fake_Measure_10

	column Fake_Measure_11
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: e064fb71-7e50-43c9-a5f0-cf5dc8a89809
		sourceColumn: Fake_Measure_11

	column Fake_Measure_12
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: cd815c20-1b82-4054-b1b8-74fa35745c19
		sourceColumn: Fake_Measure_12

	column Fake_Measure_13
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: bf59c88c-36b6-447d-8241-f83e5b4fd73c
		sourceColumn: Fake_Measure_13

	column Fake_Measure_14
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 13ce3f36-2d0b-4d02-8e44-68b5048613fa
		sourceColumn: Fake_Measure_14

	column Fake_Measure_15
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 04ca0299-5229-4b9a-b5d5-bf94facd5221
		sourceColumn: Fake_Measure_15

	column Fake_Measure_16
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: aae595d2-2481-4c4a-a2eb-b9bd53ead702
		sourceColumn: Fake_Measure_16

	column Fake_Measure_17
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 36f7f4d1-630b-433a-bd34-a91d2160491e
		sourceColumn: Fake_Measure_17

	column Fake_Measure_18
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 5647749a-c16c-4013-a2e7-7191525800df
		sourceColumn: Fake_Measure_18

	column Fake_Measure_19
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: ab1fbead-3bdf-4197-8311-c4658bcd774c
		sourceColumn: Fake_Measure_19

	column Fake_Measure_20
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: a3190cc9-719b-4db4-9df6-4166b3276d91
		sourceColumn: Fake_Measure_20

	column Fake_Measure_21
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 113eca48-801f-49f5-a1b8-50b7c31e3195
		sourceColumn: Fake_Measure_21

	column Fake_Measure_22
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 5dd3ccff-089c-4363-bac4-a13c32fd5fe7
		sourceColumn: Fake_Measure_22

	column Fake_Measure_23
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 063e899f-a4cb-4f95-888f-515d3f575a11
		sourceColumn: Fake_Measure_23

	column Fake_Measure_24
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 8d0c9e90-9169-435b-bc93-db6a017b1e0a
		sourceColumn: Fake_Measure_24

	column Fake_Measure_25
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 9f2af02f-d2a0-4c10-8ecd-26bcd45837fd
		sourceColumn: Fake_Measure_25

	column Fake_Measure_26
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1a8e8c0d-9928-4b53-9524-aed86cb32986
		sourceColumn: Fake_Measure_26

	column Fake_Measure_27
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 6fe7d72c-12c1-4414-89d2-10d94d57d5a1
		sourceColumn: Fake_Measure_27

	column Fake_Measure_28
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 7b479f96-2bcf-44f9-8927-00d1f263e0bd
		sourceColumn: Fake_Measure_28

	column Fake_Measure_29
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 827a2a6c-96e3-4622-9e7c-764a9b56fdc5
		sourceColumn: Fake_Measure_29

	column Fake_Measure_30
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1e315396-301e-4804-a6d9-3a420c5ce672
		sourceColumn: Fake_Measure_30

	column Fake_Measure_31
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 298af845-76be-483a-a60a-81850bfa4766
		sourceColumn: Fake_Measure_31

	column Fake_Measure_32
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 117ebb7f-3f59-4ad2-832f-94a3ec615021
		sourceColumn: Fake_Measure_32

	column Fake_Measure_33
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 5545dfe4-4fa8-4338-86cf-79e1274b6809
		sourceColumn: Fake_Measure_33

	column Fake_Measure_34
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 24884b05-47cf-4fc3-b71c-8a90a3aef2ce
		sourceColumn: Fake_Measure_34

	column Fake_Measure_35
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1578baf4-4cc3-4616-b1ab-503d1486a70e
		sourceColumn: Fake_Measure_35

	column Fake_Measure_36
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: c4d9685c-600e-41e8-895f-38fb074774a1
		sourceColumn: Fake_Measure_36

	column Fake_Measure_37
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 63d54504-6265-4d1a-8686-267199e1e1ef
		sourceColumn: Fake_Measure_37

	column Fake_Measure_38
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 146c6213-b385-4a26-9353-6fe1c0f85785
		sourceColumn: Fake_Measure_38

	column Fake_Measure_39
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 9933bc1e-a1a0-4bdc-823a-34645bca261f
		sourceColumn: Fake_Measure_39

	column Fake_Measure_40
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: c7c85764-b196-441c-aaa4-6c7b12007b0f
		sourceColumn: Fake_Measure_40

	column Fake_Measure_41
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 65f3bd48-7587-4c81-8f3c-b0dba3bb19be
		sourceColumn: Fake_Measure_41

	column Fake_Measure_42
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: f79669ed-bbff-4c00-838c-a1979c2a8e0b
		sourceColumn: Fake_Measure_42

	column Fake_Measure_43
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: abef6b2d-8ebc-4cde-9f57-f03c281f3d08
		sourceColumn: Fake_Measure_43

	column Fake_Measure_44
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 3c7d6652-9176-45e5-8c45-6a01a6e5a126
		sourceColumn: Fake_Measure_44

	column Fake_Measure_45
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: ec91f691-390a-4415-8c00-8bb21c4e43d9
		sourceColumn: Fake_Measure_45

	column Fake_Measure_46
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: d691dad8-0a40-4da9-b79d-c644b513baf0
		sourceColumn: Fake_Measure_46

	column Fake_Measure_47
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: c7a2d821-3f74-47a2-8fea-0d1477278ca5
		sourceColumn: Fake_Measure_47

	column Fake_Measure_48
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 95fc87cb-b52b-48c4-af09-55891abb5796
		sourceColumn: Fake_Measure_48

	column Fake_Measure_49
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 7b4451b1-b1db-41b2-8f93-95d7f4bc3f19
		sourceColumn: Fake_Measure_49

	column Fake_Measure_50
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 50094393-1033-486c-9fe7-8d49a21633b7
		sourceColumn: Fake_Measure_50

	column Fake_Measure_51
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 5b3f4d01-fc1a-4d58-ae4d-568c0ac452f5
		sourceColumn: Fake_Measure_51

	column Fake_Measure_52
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: decf1881-ba7d-47c8-9585-6d4ff2ba3157
		sourceColumn: Fake_Measure_52

	column Fake_Measure_53
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 8042a096-1f58-4dfb-9005-cac8af17324e
		sourceColumn: Fake_Measure_53

	column Fake_Measure_54
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: f11e9f52-60c6-4155-819c-f268aa8c8ade
		sourceColumn: Fake_Measure_54

	column Fake_Measure_55
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 9cee84a1-b2c4-4760-890a-34a10b3305b7
		sourceColumn: Fake_Measure_55

	column Fake_Measure_56
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: ba83de65-d461-408a-a88a-caf4d078d185
		sourceColumn: Fake_Measure_56

	column Fake_Measure_57
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 4f874bda-ca8d-4c02-a13f-fc946b7a56f0
		sourceColumn: Fake_Measure_57

	column Fake_Measure_58
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 4aafd38f-cbaa-4bb3-b133-e099326d1f8d
		sourceColumn: Fake_Measure_58

	column Fake_Measure_59
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 52838fef-c5ec-4fa7-a6f9-3a09b056c2fd
		sourceColumn: Fake_Measure_59

	column Fake_Measure_60
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 76329731-7533-4795-a3bc-3cdb1a1df3b2
		sourceColumn: Fake_Measure_60

	column Fake_Measure_61
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 082d00e7-0b7e-4ad1-8b80-6e684de4a42b
		sourceColumn: Fake_Measure_61

	column Fake_Measure_62
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 3975028b-5d32-4c1e-80f9-5b6f64b61ee8
		sourceColumn: Fake_Measure_62

	column Fake_Measure_63
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 4b486955-6417-4766-a0fd-8afb30df82c2
		sourceColumn: Fake_Measure_63

	column Fake_Measure_64
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: f1162693-34e5-41fa-8680-5d0f16827b42
		sourceColumn: Fake_Measure_64

	column Fake_Measure_65
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 47274ae0-d52f-4f04-b36a-f69ebd756971
		sourceColumn: Fake_Measure_65

	column Fake_Measure_66
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 75871db3-e936-47c9-bf70-057af8a38a1e
		sourceColumn: Fake_Measure_66

	column Fake_Measure_67
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 6db40f31-a42e-4c9c-b9a4-69a261baf3a8
		sourceColumn: Fake_Measure_67

	column Fake_Measure_68
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 8773d14b-d2da-4281-a03b-d966990fff93
		sourceColumn: Fake_Measure_68

	column Fake_Measure_69
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 75ae108f-6199-4206-88b3-1ce17a3d7a40
		sourceColumn: Fake_Measure_69

	column Fake_Measure_70
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: d15ab49f-db56-48d0-93de-99b79c39881b
		sourceColumn: Fake_Measure_70

	column Fake_Measure_71
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1062e51d-e35b-4dad-9611-ef16d8835231
		sourceColumn: Fake_Measure_71

	column Fake_Measure_72
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 03a936a6-a43a-428a-9400-a564b8ff3cdc
		sourceColumn: Fake_Measure_72

	column Fake_Measure_73
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 40cde1bd-b1a6-471a-89be-935026eb7864
		sourceColumn: Fake_Measure_73

	column Fake_Measure_74
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 506772b1-4020-458e-beae-12627b229ee3
		sourceColumn: Fake_Measure_74

	column Fake_Measure_75
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 2e3183e8-a3aa-4f94-a355-37a569da1aac
		sourceColumn: Fake_Measure_75

	column Fake_Measure_76
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 52c8ca97-345e-4b83-bb39-40dc92672e14
		sourceColumn: Fake_Measure_76

	column Fake_Measure_77
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: bdb5f11f-2a47-4bfb-b34a-c3e9cd6ae710
		sourceColumn: Fake_Measure_77

	column Fake_Measure_78
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: d21effc9-6941-419a-9d2d-ee2cb99c5360
		sourceColumn: Fake_Measure_78

	column Fake_Measure_79
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: bfd32118-68c6-4f2f-9126-8b4afdf74883
		sourceColumn: Fake_Measure_79

	column Fake_Measure_80
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1f72e0b5-e5ac-4d25-b664-33452453b0cd
		sourceColumn: Fake_Measure_80

	column Fake_Measure_81
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: caef6b19-032b-4358-b68e-f833f20feba6
		sourceColumn: Fake_Measure_81

	column Fake_Measure_82
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 33a34cf3-3f02-4335-a70b-af2f3353b1ca
		sourceColumn: Fake_Measure_82

	column Fake_Measure_83
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: dd4cda1d-20bb-48a6-b494-772165f4c322
		sourceColumn: Fake_Measure_83

	column Fake_Measure_84
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 0247f041-9604-432d-84c6-f3beacb2a008
		sourceColumn: Fake_Measure_84

	column Fake_Measure_85
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: e0cf55a7-1757-4a12-81be-b35f7dd0de2e
		sourceColumn: Fake_Measure_85

	column Fake_Measure_86
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 58f6bb08-007f-471e-a201-7bb0d7f0e58b
		sourceColumn: Fake_Measure_86

	column Fake_Measure_87
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 3944eb6e-abde-4d82-840b-3fe35d260cb3
		sourceColumn: Fake_Measure_87

	column Fake_Measure_88
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 09b2a1f7-c537-45d5-9219-5c856efd12c4
		sourceColumn: Fake_Measure_88

	column Fake_Measure_89
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: cbce0cd1-8ab8-444d-917b-1a95cff03e01
		sourceColumn: Fake_Measure_89

	column Fake_Measure_90
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: cf6f8a54-0c5a-49dd-95b8-fad0aed15ae1
		sourceColumn: Fake_Measure_90

	column Fake_Measure_91
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 959897f8-0bb0-48ca-8776-1bf4f8d1a212
		sourceColumn: Fake_Measure_91

	column Fake_Measure_92
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 873aa774-6d91-4d3d-b9e2-65bb3c85bc28
		sourceColumn: Fake_Measure_92

	column Fake_Measure_93
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: d01d531a-14cc-4d9b-921c-f33e1387b578
		sourceColumn: Fake_Measure_93

	column Fake_Measure_94
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 6489cd77-c012-48da-b1e2-78489c10f44e
		sourceColumn: Fake_Measure_94

	column Fake_Measure_95
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 80e0d6a3-d883-434e-9824-585c3ae74839
		sourceColumn: Fake_Measure_95

	column Fake_Measure_96
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1904869c-6382-4bc6-aa79-78afb77c2856
		sourceColumn: Fake_Measure_96

	column Fake_Measure_97
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 844d4e5b-b5cc-43d5-8c76-bf293ecee61f
		sourceColumn: Fake_Measure_97

	column Fake_Measure_98
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: ef8157ea-a133-4377-87aa-f744caf044fd
		sourceColumn: Fake_Measure_98

	column Fake_Measure_99
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 709f2bb1-bbbe-4c71-8318-4399aa4049f0
		sourceColumn: Fake_Measure_99

	column Fake_Measure_100
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 2631f3bc-492e-4a9f-9fc3-551fe17c879a
		sourceColumn: Fake_Measure_100

	partition sales = entity
		mode: directLake
		source
			entityName: sales
			schemaName: dbo
			expressionSource: DatabaseQuery

